//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccounterApplication.Common.LocalizationResources.Views.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ComponentsViewsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComponentsViewsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccounterApplication.Common.LocalizationResources.Views.Components.ComponentsView" +
                            "sResources", typeof(ComponentsViewsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създай нова сметка.
        /// </summary>
        public static string AddComponent {
            get {
                return ResourceManager.GetString("AddComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наличност.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрий.
        /// </summary>
        public static string DeleteComponent {
            get {
                return ResourceManager.GetString("DeleteComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промени.
        /// </summary>
        public static string EditComponent {
            get {
                return ResourceManager.GetString("EditComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средства.
        /// </summary>
        public static string Funds {
            get {
                return ResourceManager.GetString("Funds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спести/Изтегли.
        /// </summary>
        public static string SaveOrWithdraw {
            get {
                return ResourceManager.GetString("SaveOrWithdraw", resourceCulture);
            }
        }
    }
}
