//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccounterApplication.Common.LocalizationResources.Shared.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccounterApplication.Common.LocalizationResources.Shared.Messages.MessagesResourc" +
                            "es", typeof(MessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна проблем при изтриване на компонентата..
        /// </summary>
        public static string ComponenDeleteError {
            get {
                return ResourceManager.GetString("ComponenDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна проблем при добавяне на сумата..
        /// </summary>
        public static string ComponentAddAmountError {
            get {
                return ResourceManager.GetString("ComponentAddAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумата беше добавена успешно..
        /// </summary>
        public static string ComponentAddAmountSuccess {
            get {
                return ResourceManager.GetString("ComponentAddAmountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна проблем при добавяне на компонентата..
        /// </summary>
        public static string ComponentAddError {
            get {
                return ResourceManager.GetString("ComponentAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компонентата беше добавена успешно..
        /// </summary>
        public static string ComponentAddSuccess {
            get {
                return ResourceManager.GetString("ComponentAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компонентата беше изтрита успешно..
        /// </summary>
        public static string ComponentDeleteSuccess {
            get {
                return ResourceManager.GetString("ComponentDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна проблем при обновяване на компонентата..
        /// </summary>
        public static string ComponentUpdatedError {
            get {
                return ResourceManager.GetString("ComponentUpdatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компонентата беше обновена успешно..
        /// </summary>
        public static string ComponentUpdatedSuccess {
            get {
                return ResourceManager.GetString("ComponentUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте ?.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте, че искате да изтриете този разход ?.
        /// </summary>
        public static string DeleteExpenseConfirmation {
            get {
                return ResourceManager.GetString("DeleteExpenseConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте, че искате да изтриете този приход ?.
        /// </summary>
        public static string DeleteIncomeConfirmation {
            get {
                return ResourceManager.GetString("DeleteIncomeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна проблем при добавяне на разхода..
        /// </summary>
        public static string ExpenseAddError {
            get {
                return ResourceManager.GetString("ExpenseAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разходът беше добавен успешно..
        /// </summary>
        public static string ExpenseAddSuccess {
            get {
                return ResourceManager.GetString("ExpenseAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна проблем при изтриване на разхода..
        /// </summary>
        public static string ExpenseDeleteError {
            get {
                return ResourceManager.GetString("ExpenseDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разходът беше изтрит успешно..
        /// </summary>
        public static string ExpenseDeleteSuccess {
            get {
                return ResourceManager.GetString("ExpenseDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна проблем при обновяване на разхода..
        /// </summary>
        public static string ExpenseUpdatedError {
            get {
                return ResourceManager.GetString("ExpenseUpdatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разходът беше обновен успешно..
        /// </summary>
        public static string ExpenseUpdatedSuccess {
            get {
                return ResourceManager.GetString("ExpenseUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна проблем при добавяне на прихода..
        /// </summary>
        public static string MonthlyIncomeAddError {
            get {
                return ResourceManager.GetString("MonthlyIncomeAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приходът беше добавен успешно..
        /// </summary>
        public static string MonthlyIncomeAddSuccess {
            get {
                return ResourceManager.GetString("MonthlyIncomeAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна проблем при изтриване на прихода..
        /// </summary>
        public static string MonthlyIncomeDeleteError {
            get {
                return ResourceManager.GetString("MonthlyIncomeDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приходът беше изтрит успешно..
        /// </summary>
        public static string MonthlyIncomeDeleteSuccess {
            get {
                return ResourceManager.GetString("MonthlyIncomeDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна проблем при обновяване на прихода..
        /// </summary>
        public static string MonthlyIncomeUpdatedError {
            get {
                return ResourceManager.GetString("MonthlyIncomeUpdatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приходът беше обновен успешно..
        /// </summary>
        public static string MonthlyIncomeUpdatedSuccess {
            get {
                return ResourceManager.GetString("MonthlyIncomeUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна проблем при осъществяване на транзакцията..
        /// </summary>
        public static string TransactionResultError {
            get {
                return ResourceManager.GetString("TransactionResultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транзакцията беше осъществена успешно..
        /// </summary>
        public static string TransactionResultSuccess {
            get {
                return ResourceManager.GetString("TransactionResultSuccess", resourceCulture);
            }
        }
    }
}
